import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

writeFileSync(
  join(root, 'src/version.ts'),
  `// Generated by scripts/generate-version.mjs. Do not edit.\nexport const VERSION = ${JSON.stringify(pkg.version)}\n`,
)
